// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type NewTrustee struct {
	Name                  string      `json:"name"`
	Relationship          TrusteeType `json:"relationship"`
	Email                 string      `json:"email"`
	Phone                 string      `json:"phone"`
	FacebookLink          *string     `json:"facebookLink"`
	TwitterLink           *string     `json:"twitterLink"`
	AdditionalInformation *string     `json:"additionalInformation"`
}

type Trustee struct {
	ID           string      `json:"id"`
	CreatedAt    time.Time   `json:"createdAt"`
	UpdatedAt    time.Time   `json:"updatedAt"`
	Relationship TrusteeType `json:"relationship"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Phone        string      `json:"phone"`
	FacebookLink *string     `json:"facebookLink"`
	TwitterLink  *string     `json:"twitterLink"`
}

type TrusteeType string

const (
	TrusteeTypeFather        TrusteeType = "father"
	TrusteeTypeMother        TrusteeType = "mother"
	TrusteeTypeOtherRelative TrusteeType = "other_relative"
	TrusteeTypeBestFriend    TrusteeType = "best_friend"
	TrusteeTypeSchoolFriend  TrusteeType = "school_friend"
	TrusteeTypeCollegeFriend TrusteeType = "college_friend"
	TrusteeTypeOtherFriend   TrusteeType = "other_friend"
	TrusteeTypeHusband       TrusteeType = "husband"
	TrusteeTypeWife          TrusteeType = "wife"
	TrusteeTypeGirlfriend    TrusteeType = "girlfriend"
	TrusteeTypeBoyfriend     TrusteeType = "boyfriend"
	TrusteeTypeFiance        TrusteeType = "fiance"
	TrusteeTypeAcquaintance  TrusteeType = "acquaintance"
)

var AllTrusteeType = []TrusteeType{
	TrusteeTypeFather,
	TrusteeTypeMother,
	TrusteeTypeOtherRelative,
	TrusteeTypeBestFriend,
	TrusteeTypeSchoolFriend,
	TrusteeTypeCollegeFriend,
	TrusteeTypeOtherFriend,
	TrusteeTypeHusband,
	TrusteeTypeWife,
	TrusteeTypeGirlfriend,
	TrusteeTypeBoyfriend,
	TrusteeTypeFiance,
	TrusteeTypeAcquaintance,
}

func (e TrusteeType) IsValid() bool {
	switch e {
	case TrusteeTypeFather, TrusteeTypeMother, TrusteeTypeOtherRelative, TrusteeTypeBestFriend, TrusteeTypeSchoolFriend, TrusteeTypeCollegeFriend, TrusteeTypeOtherFriend, TrusteeTypeHusband, TrusteeTypeWife, TrusteeTypeGirlfriend, TrusteeTypeBoyfriend, TrusteeTypeFiance, TrusteeTypeAcquaintance:
		return true
	}
	return false
}

func (e TrusteeType) String() string {
	return string(e)
}

func (e *TrusteeType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrusteeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrusteeType", str)
	}
	return nil
}

func (e TrusteeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
